Repository AmyHong0502/plan-your-vote-cda, pull requests merged in 2019-05, with the labels that each got.

#21 Remove static data
  public/css/default.css
  src/components/MultipleChoiceQuestion/index.jsx
  src/constants/dummyData/candidates.json
  src/pages/App/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
  src/utils/api/pyv.js
  src/utils/image.js
Labels: size/L

#23 Added CI/CD feature
  .env
  azure-pipelines.yml
  jsconfig.json
  now.json
  package.json
  public/static/css/common.css
  public/static/css/default.css
  public/static/css/maple.css
  public/static/css/snowdrop.css
  src/constants/themes.js
Labels: enhancement

#22 issue #20 - Map component
  .gitignore
  docs/map.md
  package-lock.json
  package.json
  public/index.html
  src/components/Map/index.jsx
  src/constants/coordinates.json
  src/pages/selection/schedule/index.jsx
  website/i18n/en.json
Labels: size/XXL

#30 Chris localstorage issue number #28
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
Labels: size/M

#27 issue #26 - user interaction with Mapbox
  src/components/Map/details.jsx
  src/components/Map/index.jsx
  src/constants/coordinates.json
  src/pages/selection/schedule/index.jsx
Labels: size/XXL

#31 issue #29 - get distance from the user's location
  public/index.html
  src/components/Map/index.jsx
  src/utils/api/mapboxDistance.js
Labels: size/M

#32 #29 - sort polling stations by distance
  public/index.html
  src/components/Map/details.jsx
  src/components/Map/index.jsx
  src/components/Map/locations.css
Labels: size/L

#34 centralized baseURLs
  src/constants/api.js
  src/pages/selection/candidates/index.jsx
  src/utils/api/mapboxDistance.js
  src/utils/api/pyv.js
  src/utils/image.js
Labels: size/M

#35 Clean up
  src/apis/mapboxDistance.js
  src/apis/pyv.js
  src/components/Map/index.jsx
  src/constants/baseURL.js
  src/i18n/en.json
  src/i18n/ko.json
  src/i18n/zh-CN.json
  src/i18n/zh-HK.json
  src/i18n/zh-TW.json
  src/pages/App/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
Labels: enhancement

#37 Chris candidates modal
  public/static/css/default.css
  src/components/CandidateCard/index.jsx
  src/components/CandidateCard/style.css
  src/components/CandidateHeader/index.jsx
  src/components/CandidateModal/index.jsx
  src/pages/selection/candidates/index.jsx
Labels: size/L

#39 Issue #33
  README.md
  docs/map.md
  public/index.html
  public/static/css/default.css
Labels: size/M

#41 36
  src/components/Map/details.jsx
  src/components/Map/index.jsx
  src/components/Map/map.jsx
Labels: enhancement, important, size/L

#40 Candidates modal
  public/static/css/default.css
  src/components/CandidateCard/index.jsx
  src/components/CandidateModal/index.jsx
  src/pages/selection/candidates/index.jsx
Labels: size/L

#42 categorized candidates by position
  src/pages/selection/candidates/index.jsx
Labels: size/S

#43 29
  public/index.html
  src/components/Email/index.jsx
  src/pages/home/index.jsx
Labels: size/L

#44 Styled candidates subsection and re ordered candidates
  public/static/css/default.css
  src/components/CandidateModal/index.jsx
  src/components/CandidateSectionHeader/index.jsx
  src/pages/selection/candidates/index.jsx
Labels: size/L

#45 Refactor
  src/components/Footer/index.jsx
  src/components/ICS/index.jsx
  src/components/Navigation/index.jsx
  src/pages/home/index.jsx
Labels: size/L

#46 fixed key issue
  src/pages/selection/candidates/index.jsx
Labels: size/M

#47 Refactor
  src/components/CandidateModal/index.jsx
  src/components/Table/index.jsx
Labels: size/M

#48 Distance
  src/components/Map/details.jsx
  src/components/Map/index.jsx
  src/constants/baseURL.js
Labels: size/L

#50 Candidate selection
  public/static/css/default.css
  src/components/CandidateModal/index.jsx
  src/components/TotalCandidates/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
Labels: size/L

#53 Logo
  src/pages/App/index.jsx
Labels: size/S

#51 added next and back buttons to schedule and review page
  public/static/css/default.css
  src/components/CandidateSectionHeader/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
  src/pages/selection/review/index.jsx
  src/pages/selection/schedule/index.jsx
Labels: size/M

#52 implemented sessionStorage for capital page
  src/components/MultipleChoiceQuestion/index.jsx
  src/components/TotalCandidates/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
Labels: size/M

#54 Map user input
  package-lock.json
  package.json
  public/index.html
  src/components/Map/index.jsx
  src/components/Map/locations.css
  src/constants/baseURL.js
  src/pages/selection/schedule/index.jsx
Labels: size/L

#55 Map datetime
  src/components/Map/Details.jsx
  src/pages/selection/schedule/index.jsx
Labels: size/M

#56 Map cleanup
  src/components/Map/Details.jsx
  src/components/Map/locations.css
  src/constants/mapbox.js
  src/pages/selection/schedule/index.jsx
Labels: size/S

#57 Review page
  public/static/css/default.css
  src/components/CandidateReviewCard/index.jsx
  src/components/CandidateSectionHeader/index.jsx
  src/components/MultipleChoiceQuestion/index.jsx
  src/components/reviewQuestions/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
  src/pages/selection/review/index.jsx
Labels: size/L

#58 implemented sessionStorage and select and remove buttons
  src/components/Map/Details.jsx
  src/components/ReviewVoteCard/index.jsx
  src/pages/selection/review/index.jsx
  src/pages/selection/schedule/index.jsx
Labels: size/M

#59 Sort candidates
  src/pages/selection/candidates/index.jsx
Labels: size/M

#60 Update index.jsx
  src/pages/selection/candidates/index.jsx
Labels: size/S

#61 removed unused data
  src/constants/dummyData/pages.json
Labels: size/S

#62 Cleanup
  src/components/CandidateModal/index.jsx
  src/components/TotalCandidates/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/review/index.jsx
Labels: size/L

#64 refactored home component
  src/pages/home/index.jsx
Labels: size/M

#63 Cleanup review
  src/pages/selection/review/index.jsx
Labels: size/M

#65 Chris fix
  src/components/Map/Details.jsx
  src/components/SectionHeader/index.jsx
  src/pages/selection/candidates/index.jsx
  src/pages/selection/capital/index.jsx
  src/pages/selection/schedule/index.jsx
Labels: size/M

#67 Chrisfix2
  src/components/ReviewQuestions/index.jsx
  src/components/ReviewVoteCard/index.jsx
  src/components/reviewQuestions/index.jsx
  src/pages/selection/review/index.jsx
Labels: size/L
